class Solution {
        public int[] sortItems(int n, int m, int[] group, List<List<Integer>> beforeItems) {

                // Assign unique group to ungrouped items
                        for (int i = 0; i < n; i++) {
                                    if (group[i] == -1) group[i] = m++;
                                            }

                                                    List<List<Integer>> itemGraph = new ArrayList<>();
                                                            List<List<Integer>> groupGraph = new ArrayList<>();

                                                                    int[] itemIndegree = new int[n];
                                                                            int[] groupIndegree = new int[m];

                                                                                    for (int i = 0; i < n; i++) itemGraph.add(new ArrayList<>());
                                                                                            for (int i = 0; i < m; i++) groupGraph.add(new ArrayList<>());

                                                                                                    for (int i = 0; i < n; i++) {
                                                                                                                for (int prev : beforeItems.get(i)) {
                                                                                                                                itemGraph.get(prev).add(i);
                                                                                                                                                itemIndegree[i]++;

                                                                                                                                                                if (group[i] != group[prev]) {
                                                                                                                                                                                    groupGraph.get(group[prev]).add(group[i]);
                                                                                                                                                                                                        groupIndegree[group[i]]++;
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                    List<Integer> itemOrder = topoSort(itemGraph, itemIndegree, n);
                                                                                                                                                                                                                                                            List<Integer> groupOrder = topoSort(groupGraph, groupIndegree, m);

                                                                                                                                                                                                                                                                    if (itemOrder.size() == 0 || groupOrder.size() == 0)
                                                                                                                                                                                                                                                                                return new int[0];

                                                                                                                                                                                                                                                                                        Map<Integer, List<Integer>> groupMap = new HashMap<>();
                                                                                                                                                                                                                                                                                                for (int item : itemOrder) {
                                                                                                                                                                                                                                                                                                            groupMap.computeIfAbsent(group[item], k -> new ArrayList<>()).add(item);
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                            List<Integer> result = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                    for (int g : groupOrder) {
                                                                                                                                                                                                                                                                                                                                                if (groupMap.containsKey(g)) {
                                                                                                                                                                                                                                                                                                                                                                result.addAll(groupMap.get(g));
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                            return result.stream().mapToInt(i -> i).toArray();
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                    private List<Integer> topoSort(List<List<Integer>> graph, int[] indegree, int n) {
                                                                                                                                                                                                                                                                                                                                                                                                            Queue<Integer> q = new LinkedList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                    List<Integer> res = new ArrayList<>();

                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (indegree[i] == 0) q.offer(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        while (!q.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int curr = q.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.add(curr);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int nei : graph.get(curr)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (--indegree[nei] == 0) q.offer(nei);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.size() == n ? res : new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
